#!/bin/sh

# check if there have uncommited files
if [[ -z $(git status -s) ]]
then
  # run build with the gradle wrapper
  ./gradlew build
  # store the last exit code in a variable
  RESULT=$?

  # return the './gradlew build' exit code
  exit $RESULT
else
  echo "tree is dirty, please commit changes before running this"
  exit 0
fi



